// src/data/markets.ts
import { getTranslation } from '../Languages/languages'

// "Translation" is whatever shape getTranslation returns
type Translation = ReturnType<typeof getTranslation>

export interface Market {
  id: string
  name: string
  symbol: string
  color: string
  question: string
  icon: string
  currentPrice: string
  participants: number
  potSize: string
}

export const getMarkets = (t: Translation): Market[] => {
    return [
        // Football (Soccer)
 
  {
  id: 'spotify-global-1',
  name: 'Global #1',
  symbol: '',
  color: '#1DB954',
  question: 'Will “Espresso” be the #1 track on Spotify Global Top 50 by 21:00 UTC today?',
  icon: '🌍',
  currentPrice: '$150',
  participants: 42,
  potSize: '$420',
},
{
  id: 'spotify-us-1',
  name: 'US #1',
  symbol: '',
  color: '#228B22',
  question: 'Will “I Had Some Help” by Post Malone be #1 on Spotify US Top 50 at 21:00 UTC today?',
  icon: '🇺🇸',
  currentPrice: '$165',
  participants: 48,
  potSize: '$480',
},
{
  id: 'female-global-1',
  name: 'Female at #1 Global',
  symbol: '',
  color: '#C71585',
  question: 'Will the top track on Spotify Global Top 50 be by a female artist at 21:00 UTC today?',
  icon: '👩‍🎤',
  currentPrice: '$170',
  participants: 45,
  potSize: '$450',
},
{
  id: 'drake-global-top10',
  name: 'Drake in Global Top 10',
  symbol: '',
  color: '#000000',
  question: 'Will any Drake song appear in the Spotify Global Top 10 at 21:00 UTC today?',
  icon: '🦉',
  currentPrice: '$140',
  participants: 39,
  potSize: '$390',
},
{
  id: 'kpop-global-top10',
  name: 'K-pop in Top 10',
  symbol: '',
  color: '#FF69B4',
  question: 'Will any K-pop song be in Spotify Global Top 10 by 21:00 UTC today?',
  icon: '🇰🇷',
  currentPrice: '$180',
  participants: 51,
  potSize: '$510',
},
{
  id: 'newcomer-us-top10',
  name: 'New Artist US Top 10',
  symbol: '',
  color: '#4169E1',
  question: 'Will a debut artist be in Spotify US Top 10 at 21:00 UTC today?',
  icon: '🆕',
  currentPrice: '$135',
  participants: 36,
  potSize: '$360',
},
{
  id: 'latin-global-top5',
  name: 'Latin Song in Top 5',
  symbol: '',
  color: '#FFA500',
  question: 'Will a Spanish-language track be in the Spotify Global Top 5 by 21:00 UTC today?',
  icon: '🇲🇽',
  currentPrice: '$155',
  participants: 41,
  potSize: '$410',
},
{
  id: 'rap-global-top3',
  name: 'Rap in Global Top 3',
  symbol: '',
  color: '#8B0000',
  question: 'Will any rap song be in Spotify Global Top 3 by 21:00 UTC today?',
  icon: '🎤',
  currentPrice: '$160',
  participants: 43,
  potSize: '$430',
},
{
  id: 'uk-artist-global',
  name: 'UK Artist in Top 10',
  symbol: '',
  color: '#B22222',
  question: 'Will a UK artist hold a Top 10 spot on Spotify Global by 21:00 UTC today?',
  icon: '🇬🇧',
  currentPrice: '$145',
  participants: 38,
  potSize: '$380',
},
{
  id: 'billie-global-top5',
  name: 'Billie Eilish Top 5',
  symbol: '',
  color: '#9932CC',
  question: 'Will Billie Eilish be in the Spotify Global Top 5 by 21:00 UTC today?',
  icon: '👁️',
  currentPrice: '$175',
  participants: 47,
  potSize: '$470',
},
{
  id: 'afrobeats-global-top10',
  name: 'Afrobeats Global Top 10',
  symbol: '',
  color: '#006400',
  question: 'Will an Afrobeats track appear in Spotify Global Top 10 by 21:00 UTC today?',
  icon: '🇳🇬',
  currentPrice: '$160',
  participants: 42,
  potSize: '$420',
},
{
  id: 'country-us-top3',
  name: 'Country Track in US Top 3',
  symbol: '',
  color: '#DAA520',
  question: 'Will a country song be in Spotify US Top 3 at 21:00 UTC today?',
  icon: '🤠',
  currentPrice: '$130',
  participants: 34,
  potSize: '$340',
},
{
  id: 'tiktok-song-global-top5',
  name: 'TikTok Song in Global Top 5',
  symbol: '',
  color: '#FF4500',
  question: 'Will a song trending on TikTok today be in Spotify Global Top 5 at 21:00 UTC?',
  icon: '🎧',
  currentPrice: '$155',
  participants: 40,
  potSize: '$400',
},
{
  id: 'non-english-global-1',
  name: 'Non-English #1',
  symbol: '',
  color: '#808000',
  question: 'Will the #1 song on Spotify Global be in a language other than English at 21:00 UTC today?',
  icon: '🌐',
  currentPrice: '$165',
  participants: 44,
  potSize: '$440',
},
{
  id: 'album-drop-impact',
  name: 'Album Drop Surge',
  symbol: '',
  color: '#708090',
  question: 'Will any track from an album dropped in the last 24h enter Spotify Global Top 10 by 21:00 UTC today?',
  icon: '📀',
  currentPrice: '$190',
  participants: 49,
  potSize: '$490',
},
{
      id: 'london-temp-3pm',
      name: 'London 3PM ≥ 22°C',
      symbol: '🌡️',
      color: '#4682B4',
      question: 'Will the temperature at London Heathrow at 15:00 UTC today be 22°C or higher?',
      icon: '🌡️',
      currentPrice: '-',
      participants: 94,
      potSize: '$940',
    },
    {
      id: 'nyc-temp-6pm',
      name: 'New York 6PM ≥ 28°C',
      symbol: '🌡️',
      color: '#FF4500',
      question: 'Will the temperature at Central Park, NYC at 18:00 UTC today be 28°C or higher?',
      icon: '🌡️',
      currentPrice: '-',
      participants: 88,
      potSize: '$880',
    },
    {
      id: 'tokyo-temp-9am',
      name: 'Tokyo 9AM ≥ 30°C',
      symbol: '🌡️',
      color: '#FF8C00',
      question: 'Will the temperature at Tokyo Haneda Airport at 09:00 local time today be 30°C or higher?',
      icon: '🌡️',
      currentPrice: '-',
      participants: 91,
      potSize: '$910',
    },
    {
      id: 'sydney-temp-7am',
      name: 'Sydney 7AM ≤ 10°C',
      symbol: '🌡️',
      color: '#1E90FF',
      question: 'Will the temperature at Sydney Observatory Hill at 07:00 local time today be 10°C or lower?',
      icon: '🌡️',
      currentPrice: '-',
      participants: 73,
      potSize: '$730',
    },
    {
      id: 'rome-temp-12pm',
      name: 'Rome 12PM ≥ 32°C',
      symbol: '🌡️',
      color: '#CD5C5C',
      question: 'Will the temperature at Rome Ciampino Airport at 12:00 UTC today be 32°C or higher?',
      icon: '🌡️',
      currentPrice: '-',
      participants: 86,
      potSize: '$860',
    },
    {
      id: 'mumbai-temp-4pm',
      name: 'Mumbai 4PM ≥ 34°C',
      symbol: '🌡️',
      color: '#800080',
      question: 'Will the temperature at Mumbai Santa Cruz Airport at 16:00 local time today be 34°C or higher?',
      icon: '🌡️',
      currentPrice: '-',
      participants: 79,
      potSize: '$790',
    },
     {
    id: 'tesla',
    name: 'Tesla',
    symbol: 'TSLA',
    color: '#E31837',
    question: t.teslaQuestion ?? '',
    icon: '🚗',
    currentPrice: '$248.50',
    participants: 156,
    potSize: '$1,560',
  },
  {
    id: 'nvidia',
    name: 'NVIDIA',
    symbol: 'NVDA',
    color: '#76B900',
    question: t.nvidiaQuestion ?? '',
    icon: '🎮',
    currentPrice: '$876.20',
    participants: 203,
    potSize: '$2,030',
  },
  {
    id: 'sp500',
    name: 'S&P 500',
    symbol: 'SPX',
    color: '#1f77b4',
    question: t.sp500Question ?? '',
    icon: '📈',
    currentPrice: '5,987',
    participants: 78,
    potSize: '$780',
  },
  {
    id: 'apple',
    name: 'Apple',
    symbol: 'AAPL',
    color: '#A2AAAD',
    question: t.appleQuestion ?? '',
    icon: '🍎',
    currentPrice: '$190.30',
    participants: 134,
    potSize: '$1,340',
  },
  {
    id: 'google',
    name: 'Alphabet',
    symbol: 'GOOGL',
    color: '#34A853',
    question: t.googleQuestion ?? '',
    icon: '🔍',
    currentPrice: '$142.80',
    participants: 101,
    potSize: '$1,010',
  },
  {
    id: 'amazon',
    name: 'Amazon',
    symbol: 'AMZN',
    color: '#FF9900',
    question: t.amazonQuestion ?? '',
    icon: '📦',
    currentPrice: '$171.25',
    participants: 97,
    potSize: '$970',
  },
  {
    id: 'meta',
    name: 'Meta',
    symbol: 'META',
    color: '#4267B2',
    question: t.metaQuestion ?? '',
    icon: '📘',
    currentPrice: '$355.60',
    participants: 88,
    potSize: '$880',
  },
   {
    id: 'ftse100',
    name: 'FTSE 100',
    symbol: 'FTSE',
    color: '#0057B8',
    question: t.ftse100Question ?? '',
    icon: '🇬🇧',
    currentPrice: '7,624',
    participants: 48,
    potSize: '$480',
  },
  {
      id: 'us-sports-top',
      name: 'Sports',
      symbol: '',
      color: '#1DA1F2',
      question: 'Will a sports-related topic be the #1 trending topic on X in the United States at 21:00 UTC today?',
      icon: '🏈',
      currentPrice: '-',
      participants: 112,
      potSize: '$1120',
    },
    {
      id: 'global-crime-top',
      name: 'Crime',
      symbol: '',
      color: '#DC143C',
      question: 'Will a crime-related topic be the #1 global trend on X at 21:00 UTC today?',
      icon: '🚓',
      currentPrice: '-',
      participants: 98,
      potSize: '$980',
    },
    {
      id: 'us-celeb-top',
      name: 'Celebrities',
      symbol: '',
      color: '#DA70D6',
      question: 'Will a celebrity-related topic be the top US trend on X at 21:00 UTC today?',
      icon: '🎤',
      currentPrice: '-',
      participants: 107,
      potSize: '$1070',
    },
    {
      id: 'global-crypto-top',
      name: 'Crypto',
      symbol: '',
      color: '#F7931A',
      question: 'Will a crypto-related topic be the #1 global X trend at 21:00 UTC today?',
      icon: '₿',
      currentPrice: '-',
      participants: 83,
      potSize: '$830',
    },
    {
      id: 'us-trump-top3',
      name: 'Trump',
      symbol: '',
      color: '#FF4500',
      question: 'Will the word “Trump” be in the top 3 trending topics on X in the United States by 21:00 UTC today?',
      icon: '🇺🇸',
      currentPrice: '-',
      participants: 119,
      potSize: '$1190',
    },
    {
      id: 'ukraine-top10-global',
      name: 'Ukraine',
      symbol: '',
      color: '#87CEEB',
      question: 'Will the word “Ukraine” appear in the top 10 trending topics on X globally by 21:00 UTC today?',
      icon: '🌍',
      currentPrice: '-',
      participants: 94,
      potSize: '$940',
    },
    {
      id: 'kardashian-top5-us',
      name: 'Kardashians',
      symbol: '',
      color: '#FFC0CB',
      question: 'Will any Kardashian-related topic be trending in the top 5 on X in the United States by 21:00 UTC today?',
      icon: '💄',
      currentPrice: '-',
      participants: 103,
      potSize: '$1030',
    },
    {
      id: 'elon-top10-global',
      name: 'Elon Musk',
      symbol: '',
      color: '#000000',
      question: 'Will “Elon” or “Musk” be among the top 10 global trending topics on X by 21:00 UTC today?',
      icon: '🚀',
      currentPrice: '-',
      participants: 123,
      potSize: '$1230',
    },
    {
    id: 'bitcoin',
    name: 'Bitcoin',
    symbol: 'BTC',
    color: '#F7931A',
    question: t.bitcoinQuestion ?? '',
    icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Bitcoin.svg/800px-Bitcoin.svg.png',
    currentPrice: '$99,000.00', // Static price - use dynamic pricing component separately
    participants: 127,
    potSize: '$1,270',
  },
  {
    id: 'ethereum',
    name: 'Ethereum',
    symbol: 'ETH',
    color: '#627EEA',
    question: t.ethereumQuestion ?? '',
    icon:"https://dynamic-assets.coinbase.com/dbb4b4983bde81309ddab83eb598358eb44375b930b94687ebe38bc22e52c3b2125258ffb8477a5ef22e33d6bd72e32a506c391caa13af64c00e46613c3e5806/asset_icons/4113b082d21cc5fab17fc8f2d19fb996165bcce635e6900f7fc2d57c4ef33ae9.png",
    currentPrice: '$3,456',
    participants: 89,
    potSize: '$890',
  },
  {
    id: 'solana',
    name: 'Solana',
    symbol: 'SOL',
    color: '#9945FF',
    question: t.solanaQuestion ?? '',
    icon: 'https://upload.wikimedia.org/wikipedia/en/b/b9/Solana_logo.png',
    currentPrice: '$198',
    participants: 64,
    potSize: '$640',
  },
  
  {
    id: 'dogecoin',
    name: 'Dogecoin',
    symbol: 'DOGE',
    color: '#C2A633',
    question: t.dogecoinQuestion ?? '',
    icon: 'https://upload.wikimedia.org/wikipedia/en/d/d0/Dogecoin_Logo.png',
    currentPrice: '$0.075',
    participants: 72,
    potSize: '$720',
  },
  {
    id: 'cardano',
    name: 'Cardano',
    symbol: 'ADA',
    color: '#0033AD',
    question: t.cardanoQuestion ?? '',
    icon: 'https://static1.tokenterminal.com//cardano/logo.png',
    currentPrice: '$0.42',
    participants: 54,
    potSize: '$540',
  },
  {
    id: 'xrp',
    name: 'XRP',
    symbol: 'XRP',
    color: '#346AA9',
    question: t.xrpQuestion ?? '',
    icon: 'https://zengo.com/wp-content/uploads/xrp-1.png',
    currentPrice: '$0.62',
    participants: 60,
    potSize: '$600',
  },
 
  {
    id: 'litecoin',
    name: 'Litecoin',
    symbol: 'LTC',
    color: '#BEBEBE',
    question: t.litecoinQuestion ?? '',
    icon: 'https://s3.coinmarketcap.com/static/img/portraits/630c5fcaf8184351dc5c6ee5.png',
    currentPrice: '$150.25',
    participants: 45,
    potSize: '$450',
  },
  {
    id: 'polkadot',
    name: 'Polkadot',
    symbol: 'DOT',
    color: '#E6007A',
    question: t.polkadotQuestion ?? '',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/200x200/6636.png',
    currentPrice: '$6.50',
    participants: 38,
    potSize: '$380',
  },
  {
    id: 'chainlink',
    name: 'Chainlink',
    symbol: 'LINK',
    color: '#375BD2',
    question: t.chainlinkQuestion ?? '',
    icon: 'https://s2.coinmarketcap.com/static/img/coins/200x200/1975.png',
    currentPrice: '$8.75',
    participants: 50,
    potSize: '$500',
  },
  {
    id: 'chelsea-manutd',
    name: 'Chelsea vs Man United',
    symbol: '⚽️',
    color: '#034694',
    question: '',
    icon: '⚽️',
    currentPrice: '-',
    participants: 210,
    potSize: '$2,100',
  },
  {
    id: 'lakers-warriors',
    name: 'Lakers vs Warriors',
    symbol: '🏀',
    color: '#FDB927',
    question: '',
    icon: '🏀',
    currentPrice: '-',
    participants: 220,
    potSize: '$2,200',
  },
  {
    id: 'barcelona-madrid',
    name: 'Barcelona vs Real Madrid',
    symbol: '⚽️',
    color: '#A50044',
    question: '',
    icon: '⚽️',
    currentPrice: '-',
    participants: 187,
    potSize: '$1,870',
  },
  
  {
    id: 'nadal-djokovic',
    name: 'Nadal vs Djokovic',
    symbol: '🎾',
    color: '#FF4500',
    question: '',
    icon: '🎾',
    currentPrice: '-',
    participants: 140,
    potSize: '$1,400',
  },
  {
    id: 'brazil-argentina',
    name: 'Brazil vs Argentina',
    symbol: '⚽️',
    color: '#009C3B',
    question: '',
    icon: '⚽️',
    currentPrice: '-',
    participants: 315,
    potSize: '$3,150',
  },


  {
    id: 'celtics-bulls',
    name: 'Celtics vs Bulls',
    symbol: '🏀',
    color: '#007A33',
    question: '',
    icon: '🏀',
    currentPrice: '-',
    participants: 180,
    potSize: '$1,800',
  },

  
  {
    id: 'serena-williams-vs-osaka',
    name: 'Serena Williams vs Naomi Osaka',
    symbol: '🎾',
    color: '#32CD32',
    question: '',
    icon: '🎾',
    currentPrice: '-',
    participants: 130,
    potSize: '$1,300',
  },

  // Boxing
  {
    id: 'fury-joshua',
    name: 'Fury vs Joshua',
    symbol: '🥊',
    color: '#800000',
    question: '',
    icon: '🥊',
    currentPrice: '-',
    participants: 170,
    potSize: '$1,700',
  },
  {
    id: 'chiefs-buccaneers',
    name: 'Chiefs vs Buccaneers',
    symbol: '🏈',
    color: '#E31837',
    question: '',
    icon: '🏈',
    currentPrice: '-',
    participants: 190,
    potSize: '$1,900',
  },
  {
    id: 'canelo-golovkin',
    name: 'Canelo vs Golovkin',
    symbol: '🥊',
    color: '#DAA520',
    question: '',
    icon: '🥊',
    currentPrice: '-',
    participants: 150,
    potSize: '$1,500',
  },

  // NFL
  {
    id: 'patriots-packers',
    name: 'Patriots vs Packers',
    symbol: '🏈',
    color: '#002244',
    question: '',
    icon: '🏈',
    currentPrice: '-',
    participants: 200,
    potSize: '$2,000',
  },
  

  // Hockey
  {
    id: 'canadiens-mapleleafs',
    name: 'Canadiens vs Maple Leafs',
    symbol: '🏒',
    color: '#AF1E2D',
    question: '',
    icon: '🏒',
    currentPrice: '-',
    participants: 110,
    potSize: '$1,100',
  },
  {
    id: 'blackhawks-redwings',
    name: 'Blackhawks vs Red Wings',
    symbol: '🏒',
    color: '#CF0A2C',
    question: '',
    icon: '🏒',
    currentPrice: '-',
    participants: 120,
    potSize: '$1,200',
  }
]
  
    
}