// src/data/markets.ts
import { getTranslation } from '../Languages/languages'

// “Translation” is whatever shape getTranslation returns
type Translation = ReturnType<typeof getTranslation>

export interface Market {
  id: string
  name: string
  symbol: string
  color: string
  question: string
  icon: string
  currentPrice: string
  participants: number
  potSize: string
}

export const getMarkets = (t: Translation, category: String): Market[] => {



  if (category === 'sports') {
    return [
  // Football (Soccer)
  {
    id: 'chelsea-manutd',
    name: 'Chelsea vs Man United',
    symbol: '⚽️',
    color: '#034694',
    question: '',
    icon: '⚽️',
    currentPrice: '-',
    participants: 210,
    potSize: '$2,100',
  },
  {
    id: 'lakers-warriors',
    name: 'Lakers vs Warriors',
    symbol: '🏀',
    color: '#FDB927',
    question: '',
    icon: '🏀',
    currentPrice: '-',
    participants: 220,
    potSize: '$2,200',
  },
  {
    id: 'barcelona-madrid',
    name: 'Barcelona vs Real Madrid',
    symbol: '⚽️',
    color: '#A50044',
    question: '',
    icon: '⚽️',
    currentPrice: '-',
    participants: 187,
    potSize: '$1,870',
  },
  
  {
    id: 'nadal-djokovic',
    name: 'Nadal vs Djokovic',
    symbol: '🎾',
    color: '#FF4500',
    question: '',
    icon: '🎾',
    currentPrice: '-',
    participants: 140,
    potSize: '$1,400',
  },
  {
    id: 'brazil-argentina',
    name: 'Brazil vs Argentina',
    symbol: '⚽️',
    color: '#009C3B',
    question: '',
    icon: '⚽️',
    currentPrice: '-',
    participants: 315,
    potSize: '$3,150',
  },


  {
    id: 'celtics-bulls',
    name: 'Celtics vs Bulls',
    symbol: '🏀',
    color: '#007A33',
    question: '',
    icon: '🏀',
    currentPrice: '-',
    participants: 180,
    potSize: '$1,800',
  },

  
  {
    id: 'serena-williams-vs-osaka',
    name: 'Serena Williams vs Naomi Osaka',
    symbol: '🎾',
    color: '#32CD32',
    question: '',
    icon: '🎾',
    currentPrice: '-',
    participants: 130,
    potSize: '$1,300',
  },

  // Boxing
  {
    id: 'fury-joshua',
    name: 'Fury vs Joshua',
    symbol: '🥊',
    color: '#800000',
    question: '',
    icon: '🥊',
    currentPrice: '-',
    participants: 170,
    potSize: '$1,700',
  },
  {
    id: 'chiefs-buccaneers',
    name: 'Chiefs vs Buccaneers',
    symbol: '🏈',
    color: '#E31837',
    question: '',
    icon: '🏈',
    currentPrice: '-',
    participants: 190,
    potSize: '$1,900',
  },
  {
    id: 'canelo-golovkin',
    name: 'Canelo vs Golovkin',
    symbol: '🥊',
    color: '#DAA520',
    question: '',
    icon: '🥊',
    currentPrice: '-',
    participants: 150,
    potSize: '$1,500',
  },

  // NFL
  {
    id: 'patriots-packers',
    name: 'Patriots vs Packers',
    symbol: '🏈',
    color: '#002244',
    question: '',
    icon: '🏈',
    currentPrice: '-',
    participants: 200,
    potSize: '$2,000',
  },
  

  // Hockey
  {
    id: 'canadiens-mapleleafs',
    name: 'Canadiens vs Maple Leafs',
    symbol: '🏒',
    color: '#AF1E2D',
    question: '',
    icon: '🏒',
    currentPrice: '-',
    participants: 110,
    potSize: '$1,100',
  },
  {
    id: 'blackhawks-redwings',
    name: 'Blackhawks vs Red Wings',
    symbol: '🏒',
    color: '#CF0A2C',
    question: '',
    icon: '🏒',
    currentPrice: '-',
    participants: 120,
    potSize: '$1,200',
  },
]
  }

  else if (category === 'options') {
    return [
  {
    id: 'crypto',
    name: 'Crypto',
    symbol: '₿',
    color: '#FF5733',
    question: '',
    icon: '₿',
    currentPrice: '$100',
    participants: 50,
    potSize: '$500',
  },
  {
    id: 'sports',
    name: 'Sports',
    symbol: '🏆',
    color: '#33FF57',
    question: '',
    icon: '🏆',
    currentPrice: '$200',
    participants: 75,
    potSize: '$750',
  },
  {
    id: 'politics',
    name: 'Politics',
    symbol: '🏛️',
    color: '#1E90FF',
    question: '',
    icon: '🏛️',
    currentPrice: '$310',
    participants: 62,
    potSize: '$620',
  },
  {
    id: 'weather',
    name: 'Weather',
    symbol: '☁️',
    color: '#87CEEB',
    question: '',
    icon: '☁️',
    currentPrice: '$90',
    participants: 38,
    potSize: '$380',
  },
  {
    id: 'elections',
    name: 'Elections',
    symbol: '🗳️',
    color: '#FF4500',
    question: '',
    icon: '🗳️',
    currentPrice: '$470',
    participants: 94,
    potSize: '$940',
  },
  {
    id: 'tvshows',
    name: 'TV Shows',
    symbol: '📺',
    color: '#8A2BE2',
    question: '',
    icon: '📺',
    currentPrice: '$180',
    participants: 51,
    potSize: '$510',
  },
  {
    id: 'popculture',
    name: 'Pop Culture',
    symbol: '🎤',
    color: '#FF69B4',
    question: '',
    icon: '🎤',
    currentPrice: '$150',
    participants: 45,
    potSize: '$450',
  },
  {
    id: 'technews',
    name: 'Tech News',
    symbol: '💻',
    color: '#00CED1',
    question: '',
    icon: '💻',
    currentPrice: '$225',
    participants: 60,
    potSize: '$600',
  },
  {
    id: 'music',
    name: 'Music Charts',
    symbol: '🎵',
    color: '#DA70D6',
    question: '',
    icon: '🎵',
    currentPrice: '$130',
    participants: 42,
    potSize: '$420',
  },
  {
    id: 'movies',
    name: 'Box Office',
    symbol: '🎬',
    color: '#FFD700',
    question: '',
    icon: '🎬',
    currentPrice: '$270',
    participants: 58,
    potSize: '$580',
  },
  {
    id: 'finance',
    name: 'Finance',
    symbol: '💰',
    color: '#228B22',
    question: '',
    icon: '💰',
    currentPrice: '$190',
    participants: 49,
    potSize: '$490',
  },
  {
    id: 'space',
    name: 'Space & Astronomy',
    symbol: '🚀',
    color: '#7B68EE',
    question: '',
    icon: '🚀',
    currentPrice: '$140',
    participants: 36,
    potSize: '$360',
  },
  {
    id: 'fashion',
    name: 'Fashion Trends',
    symbol: '👗',
    color: '#FFB6C1',
    question: '',
    icon: '👗',
    currentPrice: '$110',
    participants: 30,
    potSize: '$300',
  },
  {
    id: 'celebs',
    name: 'Celebrity News',
    symbol: '🌟',
    color: '#FFA500',
    question: '',
    icon: '🌟',
    currentPrice: '$160',
    participants: 47,
    potSize: '$470',
  },
  {
    id: 'memecoins',
    name: 'Meme Coins',
    symbol: '🐶',
    color: '#FFC0CB',
    question: '',
    icon: '🐶',
    currentPrice: '$120',
    participants: 34,
    potSize: '$340',
  },
  {
    id: 'health',
    name: 'Health & Fitness',
    symbol: '💪',
    color: '#32CD32',
    question: '',
    icon: '💪',
    currentPrice: '$175',
    participants: 44,
    potSize: '$440',
  },
  {
    id: 'gaming',
    name: 'Gaming',
    symbol: '🎮',
    color: '#6A5ACD',
    question: '',
    icon: '🎮',
    currentPrice: '$205',
    participants: 53,
    potSize: '$530',
  },
  {
    id: 'travel',
    name: 'Travel & Tourism',
    symbol: '✈️',
    color: '#00BFFF',
    question: '',
    icon: '✈️',
    currentPrice: '$185',
    participants: 40,
    potSize: '$400',
  }
]

 }

  // Default category (financial/crypto/etc)
  return [
  {
    id: 'bitcoin',
    name: 'Bitcoin',
    symbol: '₿',
    color: '#F7931A',
    question: t.bitcoinQuestion ?? '',
    icon: '₿',
    currentPrice: '$67,234',
    participants: 127,
    potSize: '$1,270',
  },
  {
    id: 'ethereum',
    name: 'Ethereum',
    symbol: 'Ξ',
    color: '#627EEA',
    question: t.ethereumQuestion ?? '',
    icon: 'Ξ',
    currentPrice: '$3,456',
    participants: 89,
    potSize: '$890',
  },
  {
    id: 'solana',
    name: 'Solana',
    symbol: 'SOL',
    color: '#9945FF',
    question: t.solanaQuestion ?? '',
    icon: '◎',
    currentPrice: '$198',
    participants: 64,
    potSize: '$640',
  },
  {
    id: 'tesla',
    name: 'Tesla',
    symbol: 'TSLA',
    color: '#E31837',
    question: t.teslaQuestion ?? '',
    icon: '🚗',
    currentPrice: '$248.50',
    participants: 156,
    potSize: '$1,560',
  },
  {
    id: 'nvidia',
    name: 'NVIDIA',
    symbol: 'NVDA',
    color: '#76B900',
    question: t.nvidiaQuestion ?? '',
    icon: '🎮',
    currentPrice: '$876.20',
    participants: 203,
    potSize: '$2,030',
  },
  {
    id: 'sp500',
    name: 'S&P 500',
    symbol: 'SPX',
    color: '#1f77b4',
    question: t.sp500Question ?? '',
    icon: '📈',
    currentPrice: '5,987',
    participants: 78,
    potSize: '$780',
  },
  {
    id: 'apple',
    name: 'Apple',
    symbol: 'AAPL',
    color: '#A2AAAD',
    question: t.appleQuestion ?? '',
    icon: '🍎',
    currentPrice: '$190.30',
    participants: 134,
    potSize: '$1,340',
  },
  {
    id: 'google',
    name: 'Alphabet',
    symbol: 'GOOGL',
    color: '#34A853',
    question: t.googleQuestion ?? '',
    icon: '🔍',
    currentPrice: '$142.80',
    participants: 101,
    potSize: '$1,010',
  },
  {
    id: 'amazon',
    name: 'Amazon',
    symbol: 'AMZN',
    color: '#FF9900',
    question: t.amazonQuestion ?? '',
    icon: '📦',
    currentPrice: '$171.25',
    participants: 97,
    potSize: '$970',
  },
  {
    id: 'meta',
    name: 'Meta',
    symbol: 'META',
    color: '#4267B2',
    question: t.metaQuestion ?? '',
    icon: '📘',
    currentPrice: '$355.60',
    participants: 88,
    potSize: '$880',
  },
  {
    id: 'dogecoin',
    name: 'Dogecoin',
    symbol: 'DOGE',
    color: '#C2A633',
    question: t.dogecoinQuestion ?? '',
    icon: '🐶',
    currentPrice: '$0.075',
    participants: 72,
    potSize: '$720',
  },
  {
    id: 'cardano',
    name: 'Cardano',
    symbol: 'ADA',
    color: '#0033AD',
    question: t.cardanoQuestion ?? '',
    icon: '🔷',
    currentPrice: '$0.42',
    participants: 54,
    potSize: '$540',
  },
  {
    id: 'xrp',
    name: 'XRP',
    symbol: 'XRP',
    color: '#346AA9',
    question: t.xrpQuestion ?? '',
    icon: '💧',
    currentPrice: '$0.62',
    participants: 60,
    potSize: '$600',
  },
  {
    id: 'ftse100',
    name: 'FTSE 100',
    symbol: 'FTSE',
    color: '#0057B8',
    question: t.ftse100Question ?? '',
    icon: '🇬🇧',
    currentPrice: '7,624',
    participants: 48,
    potSize: '$480',
  },
  {
    id: 'gold',
    name: 'Gold',
    symbol: 'XAU',
    color: '#FFD700',
    question: t.goldQuestion ?? '',
    icon: '🥇',
    currentPrice: '$2,308',
    participants: 69,
    potSize: '$690',
  },
]
}



